
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-eirini-cloudfoundry-org-v1-lrp
  failurePolicy: Fail
  name: vlrp.kb.io
  rules:
  - apiGroups:
    - eirini.cloudfoundry.org
    apiVersions:
    - v1
    operations:
    - UPDATE
    resources:
    - lrps
  sideEffects: None
