# permissions for end users to edit lrps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: lrp-editor-role
rules:
- apiGroups:
  - eirini.cloudfoundry.org
  resources:
  - lrps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - eirini.cloudfoundry.org
  resources:
  - lrps/status
  verbs:
  - get
