# permissions for end users to view lrps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: lrp-viewer-role
rules:
- apiGroups:
  - eirini.cloudfoundry.org
  resources:
  - lrps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - eirini.cloudfoundry.org
  resources:
  - lrps/status
  verbs:
  - get
