
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - eirini.cloudfoundry.org
  resources:
  - lrps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - eirini.cloudfoundry.org
  resources:
  - lrps/finalizers
  verbs:
  - update
- apiGroups:
  - eirini.cloudfoundry.org
  resources:
  - lrps/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - eirini.cloudfoundry.org
  resources:
  - tasks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - eirini.cloudfoundry.org
  resources:
  - tasks/finalizers
  verbs:
  - update
- apiGroups:
  - eirini.cloudfoundry.org
  resources:
  - tasks/status
  verbs:
  - get
  - patch
  - update
